project_id = "ujkxdoypfazesiyjqdub"

[functions.test-r2]
verify_jwt = false

[functions.r2-storage]
verify_jwt = false

[functions.admin-plans]
verify_jwt = false

[functions.admin-settings]
verify_jwt = false

[functions.admin-storage]
verify_jwt = false
