// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujkxdoypfazesiyjqdub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqa3hkb3lwZmF6ZXNpeWpxZHViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgzNjM0NjcsImV4cCI6MjA4MzkzOTQ2N30.VoL7GY0_MMLV-7H0GHM_EKBxzvqqP_6sqlesOZO0WVc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});